import { describe, it, expect } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { NextIntlClientProvider } from 'next-intl';
import { FormProvider, useForm, useWatch } from 'react-hook-form';

import messages from '@/messages/fa.json';
import { BasePriceSection } from './BasePriceSection';
import type { ProductFormValues } from '../productEditor.schema';

const copy = messages.Commerce.Editor.BasePrice;

type Variant = ProductFormValues['variants'][number];

const BLANK: Variant = {
  valueIds: [],
  price: null,
  compare: null,
  hasDiscount: false,
  stock: null,
  infinite: false,
  mediaIds: [],
  sku: null,
  weight: null,
  salePrice: null,
  saleStartsAt: null,
  saleEndsAt: null,
  allowBackorder: false,
  isActive: true,
};

/**
 * The implicit variation every product has. A form is NEVER in the `variants: []` state — zod's
 * `min(1)` forbids it and `buildEmptyProductForm` ships this row — and it matters here because
 * this row is exactly what the card edits while the product has no axes.
 */
const solo = (over: Partial<Variant> = {}): Variant => ({ ...BLANK, ...over });

/** A row that belongs to a real axis, i.e. the state that LOCKS this card. */
const variant = (valueIds: string[]): Variant => ({ ...BLANK, valueIds, price: 1000, stock: 1 });

const emptyForm: ProductFormValues = {
  title: '',
  description: '',
  categoryId: null,
  kind: 'physical',
  finalMessage: '',
  tags: [],
  specs: [],
  collectionIds: [],
  media: [],
  basePrice: null,
  baseCompare: null,
  baseStock: null,
  baseInfinite: false,
  options: [],
  variants: [solo()],
};

/**
 * Surfaces the stored values so tests assert on the NUMBER, not the formatted text — and on BOTH
 * places the card writes: the row (what is actually saved) and the seed (what survives the first
 * axis added, since the implicit row can never be a `donorOf` match).
 */
const Probe = () => {
  const price = useWatch<ProductFormValues, 'variants.0.price'>({ name: 'variants.0.price' });
  const compare = useWatch<ProductFormValues, 'variants.0.compare'>({ name: 'variants.0.compare' });
  const seedPrice = useWatch<ProductFormValues, 'basePrice'>({ name: 'basePrice' });
  const seedCompare = useWatch<ProductFormValues, 'baseCompare'>({ name: 'baseCompare' });
  return (
    <>
      <output data-testid="row-price">{String(price)}</output>
      <output data-testid="row-compare">{String(compare)}</output>
      <output data-testid="seed-price">{String(seedPrice)}</output>
      <output data-testid="seed-compare">{String(seedCompare)}</output>
    </>
  );
};

const Harness = ({ defaults }: { defaults?: Partial<ProductFormValues> }) => {
  const form = useForm<ProductFormValues>({ defaultValues: { ...emptyForm, ...defaults } });
  return (
    <NextIntlClientProvider locale="fa" messages={messages}>
      <FormProvider {...form}>
        <BasePriceSection />
        <Probe />
      </FormProvider>
    </NextIntlClientProvider>
  );
};

const axis = {
  localKey: 'opt-1',
  name: 'رنگ',
  style: 'button' as const,
  values: [{ localKey: 'v1', value: 'قرمز' }],
};

describe('BasePriceSection', () => {
  it('stores a Persian-digit price as an English number', () => {
    render(<Harness />);

    // `fireEvent.input`, not `.change`: React maps BOTH onInput and onChange onto the native
    // `input` event, and onInput (p2e conversion) must run first — a `change` event would skip it
    // entirely, which is the whole point of CLAUDE.md §18.
    fireEvent.input(screen.getByLabelText(copy.price), { target: { value: '۴۲۰۰۰۰' } });

    expect(screen.getByTestId('row-price')).toHaveTextContent('420000');
  });

  /**
   * The bug this card had: it wrote ONLY `basePrice`, which `useVariantSync` reads when it
   * GENERATES rows. A product that never gets an axis generates nothing, so the price typed here
   * reached no variant at all and Save failed pointing at the one-row grid instead.
   */
  it('writes the price into the product’s own row, not just the seed', () => {
    render(<Harness />);

    fireEvent.input(screen.getByLabelText(copy.price), { target: { value: '۴۲۰۰۰۰' } });

    expect(screen.getByTestId('row-price')).toHaveTextContent('420000');
    // The seed is still written, because it is what the rows generated by the FIRST axis inherit.
    expect(screen.getByTestId('seed-price')).toHaveTextContent('420000');
  });

  it('strips separators and stray text a merchant pastes in', () => {
    render(<Harness />);

    fireEvent.input(screen.getByLabelText(copy.price), { target: { value: '۴۲۰,۰۰۰ تومان' } });

    expect(screen.getByTestId('row-price')).toHaveTextContent('420000');
  });

  it('stores null for a cleared field, so "no price" stays distinct from zero', () => {
    render(<Harness defaults={{ variants: [solo({ price: 5000 })] }} />);

    fireEvent.input(screen.getByLabelText(copy.price), { target: { value: '' } });

    expect(screen.getByTestId('row-price')).toHaveTextContent('null');
  });

  it('shows the row’s price back in Persian digits with separators', () => {
    render(<Harness defaults={{ variants: [solo({ price: 420000 })] }} />);

    expect(screen.getByLabelText(copy.price)).toHaveValue((420000).toLocaleString('fa-IR'));
  });

  it('locks once real variations exist, because the base price only ever seeds them', () => {
    render(
      <Harness
        defaults={{
          // Seeded so the compare field is on-sale and would otherwise be ENABLED. Without it
          // the assertion below passes for the wrong reason — a product with no compare price
          // has its compare input disabled by the discount switch, lock or no lock.
          baseCompare: 9000,
          options: [axis],
          variants: [variant(['v1'])],
        }}
      />,
    );

    expect(screen.getByLabelText(copy.price)).toBeDisabled();
    expect(screen.getByLabelText(copy.compare)).toBeDisabled();
    expect(screen.getByText(copy.locked)).toBeInTheDocument();
  });

  it('shows the SEED once locked — per-variant prices live in the grid', () => {
    render(
      <Harness
        defaults={{
          basePrice: 7000,
          options: [axis],
          variants: [variant(['v1'])],
        }}
      />,
    );

    expect(screen.getByLabelText(copy.price)).toHaveValue((7000).toLocaleString('fa-IR'));
  });

  it('stays editable for a product with one variation and no axes — that row IS the product', () => {
    render(<Harness defaults={{ options: [], variants: [solo()] }} />);

    expect(screen.getByLabelText(copy.price)).toBeEnabled();
    expect(screen.getByText(copy.hint)).toBeInTheDocument();
  });

  it('warns when the compare price is not above the sale price', () => {
    render(
      <Harness
        defaults={{ variants: [solo({ price: 5000, compare: 5000, hasDiscount: true })] }}
      />,
    );

    expect(screen.getByLabelText(copy.compare)).toHaveAttribute('data-bad', 'zero');
    expect(screen.getByText(copy.compareHint)).toBeInTheDocument();
  });

  describe('discount switch', () => {
    it('starts off for a product with no compare price, and the field is not editable', () => {
      render(<Harness />);

      expect(screen.getByLabelText(copy.hasDiscount)).not.toBeChecked();
      expect(screen.getByLabelText(copy.compare)).toBeDisabled();
    });

    it('starts on for a product that already has one', () => {
      // The edit-mode case: `mapDetailToFormValues` sets `hasDiscount` from `compareAtPrice`, so a
      // loaded discounted product must render with the switch already on.
      render(
        <Harness
          defaults={{ variants: [solo({ price: 5000, compare: 8000, hasDiscount: true })] }}
        />,
      );

      expect(screen.getByLabelText(copy.hasDiscount)).toBeChecked();
      expect(screen.getByLabelText(copy.compare)).toBeEnabled();
    });

    it('enables the field when switched on', () => {
      render(<Harness defaults={{ variants: [solo({ price: 5000 })] }} />);

      fireEvent.click(screen.getByLabelText(copy.hasDiscount));

      expect(screen.getByLabelText(copy.compare)).toBeEnabled();
    });

    it('disables the field AND clears the value when switched off', () => {
      render(
        <Harness
          defaults={{ variants: [solo({ price: 5000, compare: 8000, hasDiscount: true })] }}
        />,
      );

      fireEvent.click(screen.getByLabelText(copy.hasDiscount));

      expect(screen.getByLabelText(copy.compare)).toBeDisabled();
      // The clearing is the load-bearing half: a value left behind would still be sent on save
      // and the product would stay discounted despite the switch reading off.
      expect(screen.getByTestId('row-compare')).toHaveTextContent('null');
    });

    it('keeps the switch on when the merchant clears the field by hand', () => {
      render(
        <Harness
          defaults={{ variants: [solo({ price: 5000, compare: 8000, hasDiscount: true })] }}
        />,
      );

      fireEvent.input(screen.getByLabelText(copy.compare), { target: { value: '' } });

      // Emptying the input also drives the value to null. The switch reads the row's STORED
      // `hasDiscount` rather than `compare != null`, so it cannot flip off and disable the field
      // mid-edit, under the merchant's cursor.
      expect(screen.getByLabelText(copy.hasDiscount)).toBeChecked();
      expect(screen.getByLabelText(copy.compare)).toBeEnabled();
    });

    it('drops the mismatch warning once the discount is switched off', () => {
      render(
        <Harness
          defaults={{ variants: [solo({ price: 5000, compare: 5000, hasDiscount: true })] }}
        />,
      );
      expect(screen.getByText(copy.compareHint)).toBeInTheDocument();

      fireEvent.click(screen.getByLabelText(copy.hasDiscount));

      // A cleared, disabled field cannot violate CHK_commerce_variant_compare_gt_price, so
      // leaving the warning up would block the merchant on a field they just turned off.
      expect(screen.queryByText(copy.compareHint)).not.toBeInTheDocument();
    });

    it('cannot be touched while the card is locked by real variations', () => {
      render(
        <Harness defaults={{ baseCompare: 9000, options: [axis], variants: [variant(['v1'])] }} />,
      );

      expect(screen.getByLabelText(copy.hasDiscount)).toBeDisabled();
    });
  });
});
