import { describe, it, expect } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { NextIntlClientProvider } from 'next-intl';
import { FormProvider, useForm, useWatch } from 'react-hook-form';

import messages from '@/messages/fa.json';
import { BaseStockSection } from './BaseStockSection';
import type { ProductFormValues } from '../productEditor.schema';

const copy = messages.Commerce.Editor.BaseStock;

type Variant = ProductFormValues['variants'][number];

const BLANK: Variant = {
  valueIds: [],
  price: null,
  compare: null,
  hasDiscount: false,
  stock: null,
  infinite: false,
  mediaIds: [],
  sku: null,
  weight: null,
  salePrice: null,
  saleStartsAt: null,
  saleEndsAt: null,
  allowBackorder: false,
  isActive: true,
};

/** The implicit variation every axis-less product has — the row this card edits. */
const solo = (over: Partial<Variant> = {}): Variant => ({ ...BLANK, ...over });

/** A row that belongs to a real axis, i.e. the state that LOCKS this card. */
const variant = (valueIds: string[]): Variant => ({ ...BLANK, valueIds, price: 1000, stock: 1 });

const emptyForm: ProductFormValues = {
  title: '',
  description: '',
  categoryId: null,
  kind: 'physical',
  finalMessage: '',
  tags: [],
  specs: [],
  collectionIds: [],
  media: [],
  basePrice: null,
  baseCompare: null,
  baseStock: null,
  baseInfinite: false,
  options: [],
  variants: [solo()],
};

/** Both places the card writes: the row (what is saved) and the seed (what a new axis inherits). */
const Probe = () => {
  const stock = useWatch<ProductFormValues, 'variants.0.stock'>({ name: 'variants.0.stock' });
  const infinite = useWatch<ProductFormValues, 'variants.0.infinite'>({
    name: 'variants.0.infinite',
  });
  const seedStock = useWatch<ProductFormValues, 'baseStock'>({ name: 'baseStock' });
  const seedInfinite = useWatch<ProductFormValues, 'baseInfinite'>({ name: 'baseInfinite' });
  return (
    <>
      <output data-testid="row-stock">{String(stock)}</output>
      <output data-testid="row-infinite">{String(infinite)}</output>
      <output data-testid="seed-stock">{String(seedStock)}</output>
      <output data-testid="seed-infinite">{String(seedInfinite)}</output>
    </>
  );
};

const Harness = ({ defaults }: { defaults?: Partial<ProductFormValues> }) => {
  const form = useForm<ProductFormValues>({ defaultValues: { ...emptyForm, ...defaults } });
  return (
    <NextIntlClientProvider locale="fa" messages={messages}>
      <FormProvider {...form}>
        <BaseStockSection />
        <Probe />
      </FormProvider>
    </NextIntlClientProvider>
  );
};

const axis = {
  localKey: 'opt-1',
  name: 'رنگ',
  style: 'button' as const,
  values: [{ localKey: 'v1', value: 'قرمز' }],
};

describe('BaseStockSection', () => {
  it('stores a Persian-digit count as an English number', () => {
    render(<Harness />);

    // `fireEvent.input`, not `.change`: onInput (p2e conversion) must run first — CLAUDE.md §18.
    fireEvent.input(screen.getByLabelText(copy.label), { target: { value: '۱۲' } });

    expect(screen.getByTestId('row-stock')).toHaveTextContent('12');
  });

  /**
   * The bug this card had: it wrote ONLY `baseStock`, which `useVariantSync` reads when it
   * GENERATES rows. A product that never gets an axis generates nothing, so the count typed here
   * reached no variant at all and the merchant had to retype it into the one-row grid below.
   */
  it('writes the count into the product’s own row, not just the seed', () => {
    render(<Harness />);

    fireEvent.input(screen.getByLabelText(copy.label), { target: { value: '۱۲' } });

    expect(screen.getByTestId('row-stock')).toHaveTextContent('12');
    // The seed is still written, because it is what the row generated by the FIRST axis inherits.
    expect(screen.getByTestId('seed-stock')).toHaveTextContent('12');
  });

  it('shows the row’s count back in Persian digits', () => {
    render(<Harness defaults={{ variants: [solo({ stock: 12 })] }} />);

    expect(screen.getByLabelText(copy.label)).toHaveValue((12).toLocaleString('fa-IR'));
  });

  it('stores null for a cleared field, so "not counted yet" stays distinct from zero', () => {
    render(<Harness defaults={{ variants: [solo({ stock: 12 })] }} />);

    fireEvent.input(screen.getByLabelText(copy.label), { target: { value: '' } });

    expect(screen.getByTestId('row-stock')).toHaveTextContent('null');
  });

  describe('unlimited switch', () => {
    it('starts off, and the count is editable', () => {
      render(<Harness />);

      expect(screen.getByLabelText(copy.infinite)).not.toBeChecked();
      expect(screen.getByLabelText(copy.label)).toBeEnabled();
    });

    it('starts on for a product already saved as untracked', () => {
      // The edit-mode case: `mapDetailToFormValues` sets `infinite` from `!trackInventory`.
      render(<Harness defaults={{ variants: [solo({ infinite: true })] }} />);

      expect(screen.getByLabelText(copy.infinite)).toBeChecked();
      expect(screen.getByLabelText(copy.label)).toBeDisabled();
    });

    it('marks the row untracked and disables the count when switched on', () => {
      render(<Harness defaults={{ variants: [solo({ stock: 12 })] }} />);

      fireEvent.click(screen.getByLabelText(copy.infinite));

      expect(screen.getByTestId('row-infinite')).toHaveTextContent('true');
      expect(screen.getByTestId('seed-infinite')).toHaveTextContent('true');
      expect(screen.getByLabelText(copy.label)).toBeDisabled();
    });

    it('clears the leftover count when switched on', () => {
      render(<Harness defaults={{ variants: [solo({ stock: 12 })] }} />);

      fireEvent.click(screen.getByLabelText(copy.infinite));

      // ∞ means "not tracked". A count left behind would be sent as `initialStock` and silently
      // rewrite the ledger for a variant that has no count.
      expect(screen.getByTestId('row-stock')).toHaveTextContent('null');
      expect(screen.getByTestId('seed-stock')).toHaveTextContent('null');
    });

    it('hands the count back when switched off again', () => {
      render(<Harness defaults={{ variants: [solo({ infinite: true })] }} />);

      fireEvent.click(screen.getByLabelText(copy.infinite));

      expect(screen.getByTestId('row-infinite')).toHaveTextContent('false');
      expect(screen.getByLabelText(copy.label)).toBeEnabled();
    });

    it('swaps the hint for the unlimited one', () => {
      render(<Harness defaults={{ variants: [solo({ infinite: true })] }} />);

      expect(screen.getByText(copy.infiniteHint)).toBeInTheDocument();
      expect(screen.queryByText(copy.hint)).not.toBeInTheDocument();
    });
  });

  describe('once real variations exist', () => {
    const locked = { options: [axis], variants: [variant(['v1'])] };

    it('locks the count and the switch — per-variant stock lives in the grid', () => {
      render(<Harness defaults={locked} />);

      expect(screen.getByLabelText(copy.label)).toBeDisabled();
      expect(screen.getByLabelText(copy.infinite)).toBeDisabled();
      expect(screen.getByText(copy.locked)).toBeInTheDocument();
    });

    it('shows the SEED rather than the first row’s own count', () => {
      render(<Harness defaults={{ ...locked, baseStock: 9 }} />);

      expect(screen.getByLabelText(copy.label)).toHaveValue((9).toLocaleString('fa-IR'));
    });
  });
});
