export enum ERROR_CODES {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    PASSWORD_INVALID = 'PASSWORD_INVALID',
    PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
    PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
    ORDER_EXPIRED = 'ORDER_EXPIRED',
    ORDER_SHOP_IS_NOT_VALID = 'ORDER_SHOP_IS_NOT_VALID',
    ORDER_INVALID = 'ORDER_INVALID',
    LEAD_INSTAGRAM_NOT_FOUND = 'LEAD_INSTAGRAM_NOT_FOUND'
}
