FROM node:24.11.1-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_BACK_API_URL
ARG NEXT_PUBLIC_WS_MESSAGE
ARG NEXT_PUBLIC_WS_COMMENTS
ARG NEXT_PUBLIC_DL_URL
ARG NEXT_PUBLIC_LANDING_URL
ARG NEXT_PUBLIC_INSTAGRAM_CLIENT_ID

ENV NEXT_PUBLIC_BACK_API_URL=$NEXT_PUBLIC_BACK_API_URL \
    NEXT_PUBLIC_WS_MESSAGE=$NEXT_PUBLIC_WS_MESSAGE \
    NEXT_PUBLIC_WS_COMMENTS=$NEXT_PUBLIC_WS_COMMENTS \
    NEXT_PUBLIC_DL_URL=$NEXT_PUBLIC_DL_URL \
    NEXT_PUBLIC_LANDING_URL=$NEXT_PUBLIC_LANDING_URL \
    NEXT_PUBLIC_INSTAGRAM_CLIENT_ID=$NEXT_PUBLIC_INSTAGRAM_CLIENT_ID

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
