name: Befroosh CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Deploy Front RD
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 54321 << EOF
          cd /home/cicd/Front
          git reset --hard origin/main
          git pull origin main
          git reset --hard origin/main
          cd /home/cicd/ && ./run2.sh
          EOF

      - name: Deploy Front Main
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 54321 << EOF
          cd /home/cicd/Front
          git reset --hard origin/main
          git pull origin main
          git reset --hard origin/main
          cd /home/cicd/ && sleep 20 && ./run.sh
          EOF

      - name: Remove SSH Key
        run: rm ssh_key.pem

