name: Befroosh CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Deploy Front RD
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 54321 << EOF
          cd /home/cicd/ && nohup ./run2.sh &
          EOF

      - name: Deploy Front Main
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 54321 << EOF
          cd /home/cicd/ && nohup ./run.sh &
          EOF

      - name: Deploy Check
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 54321 << EOF
          cd /home/cicd/ && ./check.sh
          EOF

      - name: Remove SSH Key
        run: rm ssh_key.pem

